name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Oryx
        run: |
          curl -s https://raw.githubusercontent.com/microsoft/Oryx/master/build/scripts/install.sh | bash
          echo "Oryx installed"

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build app with Oryx
        run: |
          oryx build . \
            --platform python \
            --platform-version 3.10 \
            -o build_output

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "srvprtdev01"
          package: build_output
