name: Build and Deploy Python App to Azure

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Oryx
        run: |
          wget https://github.com/microsoft/Oryx/releases/download/2023-07-26.01/oryx-linux-musl-x64.tar.gz
          tar -xzf oryx-linux-musl-x64.tar.gz -C /usr/local/bin
          chmod +x /usr/local/bin/oryx
          oryx --version

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build with Oryx
        run: |
          oryx build . \
            --platform python \
            --platform-version 3.10 \
            -o build_output

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "srvprtdev01"
          package: build_output
